### ISSUE TITLE
Node sample broken

### ISSUE THREAD

**Issue by acbilimoria** [AdobeDocs/adobeio-auth#28]
```profile:adobe-jwt-node alex.bilimoria$ node --version
profile:adobe-jwt-node alex.bilimoria$ npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN adobe-jwt-node@ No repository field.
npm WARN adobe-jwt-node@ No license field.

added 62 packages from 68 contributors and audited 80 packages in 1.511s
found 0 vulnerabilities

profile:adobe-jwt-node alex.bilimoria$ npm start

> adobe-jwt-node@ start /Users/alex.bilimoria/code/adobeio-auth/JWT/samples/adobe-jwt-node
> node app.js

/Users/alex.bilimoria/code/adobeio-auth/JWT/samples/adobe-jwt-node/app.js:6
  if (err) reject(err);
           ^

ReferenceError: reject is not defined
    at /Users/alex.bilimoria/code/adobeio-auth/JWT/samples/adobe-jwt-node/app.js:6:12
    at SignStream.<anonymous> (/Users/alex.bilimoria/code/adobeio-auth/JWT/samples/adobe-jwt-node/app.js:43:16)
    at SignStream.<anonymous> (/Users/alex.bilimoria/code/adobeio-auth/JWT/samples/adobe-jwt-node/node_modules/lodash.once/index.js:71:21)
    at Object.onceWrapper (events.js:281:20)
    at SignStream.emit (events.js:193:13)
    at SignStream.sign (/Users/alex.bilimoria/code/adobeio-auth/JWT/samples/adobe-jwt-node/node_modules/jws/lib/sign-stream.js:71:10)
    at SignStream.<anonymous> (/Users/alex.bilimoria/code/adobeio-auth/JWT/samples/adobe-jwt-node/node_modules/jws/lib/sign-stream.js:46:12)
    at Object.onceWrapper (events.js:281:20)
    at DataStream.emit (events.js:193:13)
    at DataStream.<anonymous> (/Users/alex.bilimoria/code/adobeio-auth/JWT/samples/adobe-jwt-node/node_modules/jws/lib/data-stream.js:32:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adobe-jwt-node@ start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the adobe-jwt-node@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alex.bilimoria/.npm/_logs/2019-04-18T22_15_11_347Z-debug.log
profile:adobe-jwt-node alex.bilimoria$ npm --version
6.9.0
profile:adobe-jwt-node alex.bilimoria$ node --version
v11.14.0
profile:adobe-jwt-node alex.bilimoria$

**Comment by hirenoble** [comment]
@acbilimoria thanks for reporting. the same has been fixed. Please pull the latest and let us know if any issues.

**Comment by acbilimoria** [comment]
@hirenoble Thank you for fixing that.  I'm getting another code error:

```C02YD2DNJGH6:adobe-jwt-node alex.bilimoria$ npm start

> adobe-jwt-node@ start /Users/alex.bilimoria/code/adobeio-auth/JWT/samples/adobe-jwt-node
> node app.js

Error occured: Error: error:09091064:PEM routines:PEM_read_bio_ex:bad base64 decode
JWT Token generated: undefined
Trying to get an access token using request: {"uri":"https://ims-na1.adobelogin.com/ims/exchange/jwt/","headers":{"content-type":"multipart/form-data","cache-control":"no-cache"},"formData":{"client_id":"670b24b901af4a35a8dff464b.....","client_secret":"dc5d1e7e-9216-46e2-b8d0-ae43......."}}
/Users/alex.bilimoria/code/adobeio-auth/JWT/samples/adobe-jwt-node/node_modules/form-data/lib/form_data.js:226
  } else if (options.filename || value.name || value.path) {
                                       ^

TypeError: Cannot read property 'name' of undefined
    at FormData._getContentDisposition (/Users/alex.bilimoria/code/adobeio-auth/JWT/samples/adobe-jwt-node/node_modules/form-data/lib/form_data.js:226:40)
    at FormData._multiPartHeader (/Users/alex.bilimoria/code/adobeio-auth/JWT/samples/adobe-jwt-node/node_modules/form-data/lib/form_data.js:177:33)
    at FormData.append (/Users/alex.bilimoria/code/adobeio-auth/JWT/samples/adobe-jwt-node/node_modules/form-data/lib/form_data.js:70:21)
    at appendFormValue (/Users/alex.bilimoria/code/adobeio-auth/JWT/samples/adobe-jwt-node/node_modules/request/request.js:326:21)
    at Request.init (/Users/alex.bilimoria/code/adobeio-auth/JWT/samples/adobe-jwt-node/node_modules/request/request.js:337:11)
    at new Request (/Users/alex.bilimoria/code/adobeio-auth/JWT/samples/adobe-jwt-node/node_modules/request/request.js:127:8)
    at request (/Users/alex.bilimoria/code/adobeio-auth/JWT/samples/adobe-jwt-node/node_modules/request/index.js:53:10)
    at Function.post (/Users/alex.bilimoria/code/adobeio-auth/JWT/samples/adobe-jwt-node/node_modules/request/index.js:61:12)
    at SignStream.<anonymous> (/Users/alex.bilimoria/code/adobeio-auth/JWT/samples/adobe-jwt-node/app.js:69:15)
    at SignStream.<anonymous> (/Users/alex.bilimoria/code/adobeio-auth/JWT/samples/adobe-jwt-node/node_modules/lodash.once/index.js:71:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adobe-jwt-node@ start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the adobe-jwt-node@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alex.bilimoria/.npm/_logs/2019-04-19T13_44_44_864Z-debug.log
C02YD2DNJGH6:adobe-jwt-node alex.bilimoria$

**Comment by hirenoble** [comment]
Hi @acbilimoria,

We had recently published a node module @adobe/jwt-auth to ease the generation of jwt and access token for JWT authentication flow.

I have updated the sample code to use the @adobe/jwt-auth. Please try this and let me know if any issues. Also, please make sure that you copy the entire content of your private key .key or .pem file.

**Comment by acbilimoria** [comment]
@hirenoble I pulled master, ran npm install, and npm start.  I then updated the config key names from snake case to camel case to reflect the new standard.

Here's what I get:

```C02YD2DNJGH6:node-auth alex.bilimoria$ node app.js
undefined

**Comment by hirenoble** [comment]
@acbilimoria, Do you have some time now let's have a quick call. https://bluejeans.com/3853452738

**Comment by acbilimoria** [comment]
@hirenoble how about 10:30 am MST?

**Comment by hirenoble** [comment]
@acbilimoria Works! see you then.

**Comment by hirenoble** [comment]
@acbilimoria I have updated the version in dependencies in package.json for @adobe/jwt-auth. This should solve the problem and you should be able to use full metascope with url. Please pull the latest and let me know if any issues.
