### ISSUE TITLE
The NodeJS sample is not working

### ISSUE THREAD

**Issue by suvadeepdey** [AdobeDocs/adobeio-auth#51]
I am trying to make this work on a windows laptop. After cloning the stage branch and trying to execute the command node app.js after doing npm install, I am getting the below error
(node:11608) UnhandledPromiseRejectionWarning: Error: error:0909006C:PEM routines:get_name:no start line
    at Sign.sign (internal/crypto/sig.js:80:26)
    at Object.sign (C:\SUVA_DATA\centralized-business-services\adobeio-auth\JWT\samples\adobe-jwt-node\node_modules\jwa\index.js:152:45)
    at Object.jwsSign [as sign] (C:\SUVA_DATA\centralized-business-services\adobeio-auth\JWT\samples\adobe-jwt-node\node_modules\jws\lib\sign-stream.js:32:24)
    at Object.module.exports [as sign] (C:\SUVA_DATA\centralized-business-services\adobeio-auth\JWT\samples\adobe-jwt-node\node_modules\jsonwebtoken\sign.js:204:16)
    at authorize (C:\SUVA_DATA\centralized-business-services\adobeio-auth\JWT\samples\adobe-jwt-node\node_modules\@adobe\jwt-auth\index.js:63:17)
    at Object.<anonymous> (C:\SUVA_DATA\centralized-business-services\adobeio-auth\JWT\samples\adobe-jwt-node\app.js:6:5)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
(node:11608) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:11608) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Can you please throw some light on the same.

**Comment by hirenoble** [comment]
Hi @suvadeepdey,

I have validated the NodeJS sample and able to generate the access token. Looking at the error it seems the private key certificate isn't correct. Let me know if you are still facing the issue.
![image](https://user-images.githubusercontent.com/3747836/71042056-f2b98480-20e7-11ea-94b0-c0b29bbe02c5.png)
